### ISSUE TITLE
resou插件的zhrs、wbrs、dyrs执行报错

### ISSUE THREAD

**Issue by ljh19930603** [Xtao-Labs/PagerMaid_Plugins#171]
1、-zhrs报错
```
# Generated: 09:13 24/06/2021. 
# Message: 
-----BEGIN TARGET MESSAGE-----
-zhrs
-----END TARGET MESSAGE-----
# Traceback: 
-----BEGIN TRACEBACK-----
Traceback (most recent call last):
  File "/pagermaid/workdir/pagermaid/listener.py", line 62, in handler
    await function(context)
  File "/pagermaid/workdir/plugins/resou.py", line 14, in netease
    res = '知乎实时热搜榜：' + '\n\n1.' + '「<a href=' + data['list']['1']['url'] + '>' + data['list']['1'][
TypeError: list indices must be integers or slices, not str"""

-----END TRACEBACK-----
# Error: "list indices must be integers or slices, not str". 
```

2、-wbrs报错
```
# Generated: 09:13 24/06/2021. 
# Message: 
-----BEGIN TARGET MESSAGE-----
-wbrs
-----END TARGET MESSAGE-----
# Traceback: 
-----BEGIN TRACEBACK-----
Traceback (most recent call last):
  File "/pagermaid/workdir/pagermaid/listener.py", line 62, in handler
    await function(context)
  File "/pagermaid/workdir/plugins/resou.py", line 37, in netease
    res = '微博实时热搜榜：' + '\n\n1.' + '「<a href=' + data['list']['1']['url'] + '>' + data['list']['1'][
TypeError: list indices must be integers or slices, not str

-----END TRACEBACK-----
# Error: "list indices must be integers or slices, not str". 
```

3、dyrs报错
```# Generated: 09:25 24/06/2021. 
# Message: 
-----BEGIN TARGET MESSAGE-----
-dyrs
-----END TARGET MESSAGE-----
# Traceback: 
-----BEGIN TRACEBACK-----
Traceback (most recent call last):
  File "/pagermaid/workdir/pagermaid/listener.py", line 62, in handler
    await function(context)
  File "/pagermaid/workdir/plugins/resou.py", line 64, in netease
    res = '抖音实时热搜榜：' + '\n\n1.' + data['list']['1']['name'] + '  热度：' + str(data['list']['1']['hot']) + '\n2.' + \
TypeError: list indices must be integers or slices, not str

-----END TRACEBACK-----
# Error: "list indices must be integers or slices, not str". ```

**Comment by xtaodada** [comment]
@ljh19930603 此插件已停止维护，请等待有缘人更新。

**Comment by monsterxcn** [comment]
我这里好像已经修好了，Python 版本是 3.8.10。如果可以的话我来 PR ？🥰

![Tested at 20210713184414](https://i.loli.net/2021/07/13/zf9axLlFONVmdAS.png)

**Comment by xtaodada** [comment]
@monsterxcn 欢迎大佬 pr ！
